### ISSUE TITLE
Licence for pictures ?

### ISSUE THREAD

**Issue by pyrog** [openchargemap/ocm-data#1]
Is it possible to reuse pictures in other projects ?

**Comment by webprofusion-chrisc** [comment]
All images are Creative Commons CC-BY-SA 4.0
https://creativecommons.org/licenses/by-sa/4.0/

This mainly means you need to attribute them back to Open Charge Map and if possible the username of the originator , ideally with a link so people can go to the source.

**Comment by webprofusion-chrisc** [comment]
Also, please don't bulk copy images if you can avoid it You can technically do this but it costs us money for the data transfer from AWS S3.

**Comment by hughsheehy** [comment]
Hey - just to check if it's ok to create a map like this. https://public.tableau.com/shared/ZZHQ9Y8R5?:display_count=y&:origin=viz_share_link

**Comment by webprofusion-chrisc** [comment]
@hughsheehy yes there's no problem with licensing but it does matter how it pulls the data and how often, for instance yesterday someone running a data integration server spammed the API for a full dataset 250k times, so that's a quick way to get banned! Ideally visualisation will cache their own copy of the data.

**Comment by webprofusion-chrisc** [comment]
@hughsheehy  very cool map by the way, can I share it via twitter?

**Comment by hughsheehy** [comment]
@webprofusion-chrisc  

Fire ahead and share. I embedded it on my own page too. https://www.hughsheehy.com/reading/worldwide-ecar-charging-points. And I added some interesting charts. EU looks way ahead in terms of installed recharge capacity. 

As for the data, I download the data from Github and then use a static copy to create the map. I'm not hitting the API or Github.  I'll update the data every few weeks. 

If I should add more licence notices let me know!

**Comment by webprofusion-chrisc** [comment]
Cool, and as you say in the blog it's a good way to find weird data points - I found some data where the kw should be 9.6 not 9600 :)

**Comment by hughsheehy** [comment]
> Cool, and as you say in the blog it's a good way to find weird data points - I found some data where the kw should be 9.6 not 9600 :)

I'd previously looked at the UK official data (from the UK .gov.uk site). There are charging points in mid-Atlantic. In the North Sea.  And sometimes just a couple of hundred metres from where they actually are.
