### ISSUE TITLE
GB/T 20234.2 is Type 2

### ISSUE THREAD

**Issue by pyrog** [openchargemap/ocm-data#2]
According to wikipedia, [Guobiao standard  GB/T_20234.2-2015](https://en.wikipedia.org/?title=GB/T_20234.2-2015&redirect=no) is [Type 2](https://en.wikipedia.org/wiki/Type_2_connector). 😉

**Comment by webprofusion-chrisc** [comment]
Thanks, so it looks like these connectors are the same shape as Type 2 but have different wiring and control, so they're not exactly Type 2 and should be defined as their own connector type. This implies there would be a socket-only and tethered (cable supplied) version of the connection for the purpose of our database.

http://en.wikibedia.ru/wiki/GB/T_20234.2-2015

[Edit] As we already have definitions for GB-T AC - GB/T 20234.2 (Socket), GB-T AC - GB/T 20234.2 (Tethered Cable) and GB-T DC - GB/T 20234.3 there doesn't appear to be anything that needs to change.

**Comment by webprofusion-chrisc** [comment]
Here also is a nice example with lots of different connectors and their specifications: https://stevenengineering.com/tech_support/PDFs/67SACC_E-MOBILITY-CHARGING.pdf
