### ISSUE TITLE
Charging stations data - OlifeEnergy

### ISSUE THREAD

**Issue by dusekp** [openchargemap/ocm-data#9]
Hello,
can you please import our charging stations data into OCM?
OlifeEnergy (https://olife-energy.net)

Here you can find zipped csv file: [OlifeEnergy_charging_stations.zip](https://github.com/openchargemap/ocm-data/files/6697008/OlifeEnergy_charging_stations.zip)

Thanks in advance!
Petr

**Comment by webprofusion-chrisc** [comment]
Thanks Petr, I have imported the data you have contributed now. Subsequent edits should be made directly on https://map.openchargemap.io

**Comment by dusekp** [comment]
Hi Christopher,
thanks for import. Unfortunately there are some issues. 
Mostly there is wrong connector types. 
We have sometimes 2x charger at the same place and there is only 1 charger imported in map. 
All connectors in map are socket only but we dont have socket only connectors. This is maybe our mistake - I dont know where should be this information in CSV file.

I will try to correct by "brutal force" - I will edit charger parameters directly in map.
So I am only giving you feedback.

Petr Dusek

**Comment by webprofusion-chrisc** [comment]
Thanks, which username are you using? I can make you a country editor so your edits take effect more quickly (no review required).

**Comment by dusekp** [comment]
My username is "dusekp". Thanks!
